// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eniaqvgmedobthosutaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuaWFxdmdtZWRvYnRob3N1dGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MTc3MDQsImV4cCI6MjA0OTk5MzcwNH0.1ikglFv4iyvApUJajK-Q5Noe1mrJE4eovK_A1GV4X0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);